name: 'twitter_ads'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  twitter_ads:
    materialized: 'table'

vars:
  twitter_ads:
    twitter_line_item_history: "{{ ref('stg_twitter_ads__line_item_history') }}"
    twitter_promoted_tweet_report: "{{ ref('stg_twitter_ads__promoted_tweet_report') }}"
    twitter_promoted_tweet_history: "{{ ref('stg_twitter_ads__promoted_tweet_history')}}"
    twitter_tweet_url: "{{ ref('stg_twitter_ads__tweet_url') }}"
    twitter_account_history: "{{ ref('stg_twitter_ads__account_history') }}"
    twitter_campaign_history: "{{ ref('stg_twitter_ads__campaign_history') }}"