name: 'twitter_ads'
version: '0.9.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  twitter_ads:
    +schema: twitter_ads
    +materialized: table
vars:
  twitter_ads:
    line_item_history: "{{ ref('stg_twitter_ads__line_item_history') }}"
    promoted_tweet_report: "{{ ref('stg_twitter_ads__promoted_tweet_report') }}"
    promoted_tweet_history: "{{ ref('stg_twitter_ads__promoted_tweet_history') }}"
    tweet_url: "{{ ref('stg_twitter_ads__tweet_url') }}"
    account_history: "{{ ref('stg_twitter_ads__account_history') }}"
    campaign_history: "{{ ref('stg_twitter_ads__campaign_history') }}"
    tweet: "{{ ref('stg_twitter_ads__tweet') }}"
    campaign_report: "{{ ref('stg_twitter_ads__campaign_report') }}"
    line_item_report: "{{ ref('stg_twitter_ads__line_item_report') }}"
    line_item_keywords_report: "{{ ref('stg_twitter_ads__line_item_keywords_report') }}"
    campaign_locations_report: "{{ ref('stg_twitter_ads__campaign_locations_report') }}"
    campaign_regions_report: "{{ ref('stg_twitter_ads__campaign_regions_report') }}"
    twitter_ads__campaign_report_passthrough_metrics: []
    twitter_ads__line_item_report_passthrough_metrics: []
    twitter_ads__line_item_keywords_report_passthrough_metrics: []
    twitter_ads__promoted_tweet_report_passthrough_metrics: []
    twitter_ads__campaign_locations_report_passthrough_metrics: []
    twitter_ads__campaign_regions_report_passthrough_metrics: []

  twitter_ads__conversion_fields:
    - conversion_purchases_metric
    - conversion_custom_metric
  twitter_ads__conversion_sale_amount_fields:
    - conversion_purchases_sale_amount
    - conversion_custom_sale_amount