name: 'twitter_ads'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
models:
  twitter_ads:
    +schema: twitter_ads
    +materialized: table
vars:
  twitter_ads:
    twitter_line_item_history: "{{ ref('stg_twitter_ads__line_item_history') }}"
    twitter_promoted_tweet_report: "{{ ref('stg_twitter_ads__promoted_tweet_report') }}"
    twitter_promoted_tweet_history: "{{ ref('stg_twitter_ads__promoted_tweet_history') }}"
    twitter_tweet_url: "{{ ref('stg_twitter_ads__tweet_url') }}"
    twitter_account_history: "{{ ref('stg_twitter_ads__account_history') }}"
    twitter_campaign_history: "{{ ref('stg_twitter_ads__campaign_history') }}"

