name: 'twitter_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2
snapshot-paths: ["snapshots"]

vars:
  twitter_ads_source:
    account_history: "{{ ref('twitter_account_history_data') }}"
    campaign_history: "{{ ref('twitter_campaign_history_data') }}"
    line_item_history: "{{ ref('twitter_line_item_history_data') }}"
    promoted_tweet_history: "{{ ref('twitter_promoted_tweet_history_data') }}"
    promoted_tweet_report: "{{ ref('twitter_promoted_tweet_report_data') }}"
    tweet_url: "{{ ref('twitter_tweet_url_data') }}"

seeds:
  twitter_integration_tests:
    twitter_tweet_url_data:
      +column_types:
        tweet_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    twitter_promoted_tweet_history_data:
      +column_types:
        tweet_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
